version: '3.9'

services:
  suitecrm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suitecrm
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/SuiteCRM
      - vendor_data:/var/www/html/vendor
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/SuiteCRM
      # --- OIDC envs used by entrypoint ---
      - OIDC_ISSUER=http://keycloak:8080/realms/suitecrm/.well-known/openid-configuration
      - OIDC_CLIENT_ID=suitecrm-app
      - OIDC_CLIENT_SECRET=aIIitQlojjXFfxwU89gfbWqb1uFLx6M2
      - OIDC_REDIRECT_URI=http://localhost:8080/oidc/callback
      - OIDC_CRYPTO_PASSPHRASE=7f9b2a59b4c23a6f3dbbb8e5a9125c23719a4f3d6f2818f8c38a5726b94c94e1
      - OIDC_REMOTE_USER_CLAIM=marinelasharka
    working_dir: /var/www/html/SuiteCRM

  mariadb:
    image: mariadb:10.5
    container_name: suitecrm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm
      MYSQL_PASSWORD: suitecrm_pass
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: suitecrm-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpass

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command: start-dev
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_pass
    volumes:
      - keycloak_data:/var/lib/postgresql/data

volumes:
  mariadb_data:
  vendor_data:
  keycloak_data:
